/**
 * CountryType2.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package es.gob.agenciatributaria.www2.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.SuministroInformacion_xsd;

public class CountryType2 implements java.io.Serializable {
    private java.lang.String _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected CountryType2(java.lang.String value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final java.lang.String _AF = "AF";
    public static final java.lang.String _AL = "AL";
    public static final java.lang.String _DE = "DE";
    public static final java.lang.String _AD = "AD";
    public static final java.lang.String _AO = "AO";
    public static final java.lang.String _AI = "AI";
    public static final java.lang.String _AQ = "AQ";
    public static final java.lang.String _AG = "AG";
    public static final java.lang.String _SA = "SA";
    public static final java.lang.String _DZ = "DZ";
    public static final java.lang.String _AR = "AR";
    public static final java.lang.String _AM = "AM";
    public static final java.lang.String _AW = "AW";
    public static final java.lang.String _AU = "AU";
    public static final java.lang.String _AT = "AT";
    public static final java.lang.String _AZ = "AZ";
    public static final java.lang.String _BS = "BS";
    public static final java.lang.String _BH = "BH";
    public static final java.lang.String _BD = "BD";
    public static final java.lang.String _BB = "BB";
    public static final java.lang.String _BE = "BE";
    public static final java.lang.String _BZ = "BZ";
    public static final java.lang.String _BJ = "BJ";
    public static final java.lang.String _BM = "BM";
    public static final java.lang.String _BY = "BY";
    public static final java.lang.String _BO = "BO";
    public static final java.lang.String _BA = "BA";
    public static final java.lang.String _BW = "BW";
    public static final java.lang.String _BV = "BV";
    public static final java.lang.String _BR = "BR";
    public static final java.lang.String _BN = "BN";
    public static final java.lang.String _BG = "BG";
    public static final java.lang.String _BF = "BF";
    public static final java.lang.String _BI = "BI";
    public static final java.lang.String _BT = "BT";
    public static final java.lang.String _CV = "CV";
    public static final java.lang.String _KY = "KY";
    public static final java.lang.String _KH = "KH";
    public static final java.lang.String _CM = "CM";
    public static final java.lang.String _CA = "CA";
    public static final java.lang.String _CF = "CF";
    public static final java.lang.String _CC = "CC";
    public static final java.lang.String _CO = "CO";
    public static final java.lang.String _KM = "KM";
    public static final java.lang.String _CG = "CG";
    public static final java.lang.String _CD = "CD";
    public static final java.lang.String _CK = "CK";
    public static final java.lang.String _KP = "KP";
    public static final java.lang.String _KR = "KR";
    public static final java.lang.String _CI = "CI";
    public static final java.lang.String _CR = "CR";
    public static final java.lang.String _HR = "HR";
    public static final java.lang.String _CU = "CU";
    public static final java.lang.String _TD = "TD";
    public static final java.lang.String _CZ = "CZ";
    public static final java.lang.String _CL = "CL";
    public static final java.lang.String _CN = "CN";
    public static final java.lang.String _CY = "CY";
    public static final java.lang.String _CW = "CW";
    public static final java.lang.String _DK = "DK";
    public static final java.lang.String _DM = "DM";
    public static final java.lang.String _DO = "DO";
    public static final java.lang.String _EC = "EC";
    public static final java.lang.String _EG = "EG";
    public static final java.lang.String _AE = "AE";
    public static final java.lang.String _ER = "ER";
    public static final java.lang.String _SK = "SK";
    public static final java.lang.String _SI = "SI";
    public static final java.lang.String _ES = "ES";
    public static final java.lang.String _US = "US";
    public static final java.lang.String _EE = "EE";
    public static final java.lang.String _ET = "ET";
    public static final java.lang.String _FO = "FO";
    public static final java.lang.String _PH = "PH";
    public static final java.lang.String _FI = "FI";
    public static final java.lang.String _FJ = "FJ";
    public static final java.lang.String _FR = "FR";
    public static final java.lang.String _GA = "GA";
    public static final java.lang.String _GM = "GM";
    public static final java.lang.String _GE = "GE";
    public static final java.lang.String _GS = "GS";
    public static final java.lang.String _GH = "GH";
    public static final java.lang.String _GI = "GI";
    public static final java.lang.String _GD = "GD";
    public static final java.lang.String _GR = "GR";
    public static final java.lang.String _GL = "GL";
    public static final java.lang.String _GU = "GU";
    public static final java.lang.String _GT = "GT";
    public static final java.lang.String _GG = "GG";
    public static final java.lang.String _GN = "GN";
    public static final java.lang.String _GQ = "GQ";
    public static final java.lang.String _GW = "GW";
    public static final java.lang.String _GY = "GY";
    public static final java.lang.String _HT = "HT";
    public static final java.lang.String _HM = "HM";
    public static final java.lang.String _HN = "HN";
    public static final java.lang.String _HK = "HK";
    public static final java.lang.String _HU = "HU";
    public static final java.lang.String _IN = "IN";
    public static final java.lang.String _ID = "ID";
    public static final java.lang.String _IR = "IR";
    public static final java.lang.String _IQ = "IQ";
    public static final java.lang.String _IE = "IE";
    public static final java.lang.String _IM = "IM";
    public static final java.lang.String _IS = "IS";
    public static final java.lang.String _IL = "IL";
    public static final java.lang.String _IT = "IT";
    public static final java.lang.String _JM = "JM";
    public static final java.lang.String _JP = "JP";
    public static final java.lang.String _JE = "JE";
    public static final java.lang.String _JO = "JO";
    public static final java.lang.String _KZ = "KZ";
    public static final java.lang.String _KE = "KE";
    public static final java.lang.String _KG = "KG";
    public static final java.lang.String _KI = "KI";
    public static final java.lang.String _KW = "KW";
    public static final java.lang.String _LA = "LA";
    public static final java.lang.String _LS = "LS";
    public static final java.lang.String _LV = "LV";
    public static final java.lang.String _LB = "LB";
    public static final java.lang.String _LR = "LR";
    public static final java.lang.String _LY = "LY";
    public static final java.lang.String _LI = "LI";
    public static final java.lang.String _LT = "LT";
    public static final java.lang.String _LU = "LU";
    public static final java.lang.String _XG = "XG";
    public static final java.lang.String _MO = "MO";
    public static final java.lang.String _MK = "MK";
    public static final java.lang.String _MG = "MG";
    public static final java.lang.String _MY = "MY";
    public static final java.lang.String _MW = "MW";
    public static final java.lang.String _MV = "MV";
    public static final java.lang.String _ML = "ML";
    public static final java.lang.String _MT = "MT";
    public static final java.lang.String _FK = "FK";
    public static final java.lang.String _MP = "MP";
    public static final java.lang.String _MA = "MA";
    public static final java.lang.String _MH = "MH";
    public static final java.lang.String _MU = "MU";
    public static final java.lang.String _MR = "MR";
    public static final java.lang.String _YT = "YT";
    public static final java.lang.String _UM = "UM";
    public static final java.lang.String _MX = "MX";
    public static final java.lang.String _FM = "FM";
    public static final java.lang.String _MD = "MD";
    public static final java.lang.String _MC = "MC";
    public static final java.lang.String _MN = "MN";
    public static final java.lang.String _ME = "ME";
    public static final java.lang.String _MS = "MS";
    public static final java.lang.String _MZ = "MZ";
    public static final java.lang.String _MM = "MM";
    public static final java.lang.String _NA = "NA";
    public static final java.lang.String _NR = "NR";
    public static final java.lang.String _CX = "CX";
    public static final java.lang.String _NP = "NP";
    public static final java.lang.String _NI = "NI";
    public static final java.lang.String _NE = "NE";
    public static final java.lang.String _NG = "NG";
    public static final java.lang.String _NU = "NU";
    public static final java.lang.String _NF = "NF";
    public static final java.lang.String _NO = "NO";
    public static final java.lang.String _NC = "NC";
    public static final java.lang.String _NZ = "NZ";
    public static final java.lang.String _IO = "IO";
    public static final java.lang.String _OM = "OM";
    public static final java.lang.String _NL = "NL";
    public static final java.lang.String _BQ = "BQ";
    public static final java.lang.String _PK = "PK";
    public static final java.lang.String _PW = "PW";
    public static final java.lang.String _PA = "PA";
    public static final java.lang.String _PG = "PG";
    public static final java.lang.String _PY = "PY";
    public static final java.lang.String _PE = "PE";
    public static final java.lang.String _PN = "PN";
    public static final java.lang.String _PF = "PF";
    public static final java.lang.String _PL = "PL";
    public static final java.lang.String _PT = "PT";
    public static final java.lang.String _PR = "PR";
    public static final java.lang.String _QA = "QA";
    public static final java.lang.String _GB = "GB";
    public static final java.lang.String _RW = "RW";
    public static final java.lang.String _RO = "RO";
    public static final java.lang.String _RU = "RU";
    public static final java.lang.String _SB = "SB";
    public static final java.lang.String _SV = "SV";
    public static final java.lang.String _WS = "WS";
    public static final java.lang.String _AS = "AS";
    public static final java.lang.String _KN = "KN";
    public static final java.lang.String _SM = "SM";
    public static final java.lang.String _SX = "SX";
    public static final java.lang.String _PM = "PM";
    public static final java.lang.String _VC = "VC";
    public static final java.lang.String _SH = "SH";
    public static final java.lang.String _LC = "LC";
    public static final java.lang.String _ST = "ST";
    public static final java.lang.String _SN = "SN";
    public static final java.lang.String _RS = "RS";
    public static final java.lang.String _SC = "SC";
    public static final java.lang.String _SL = "SL";
    public static final java.lang.String _SG = "SG";
    public static final java.lang.String _SY = "SY";
    public static final java.lang.String _SO = "SO";
    public static final java.lang.String _LK = "LK";
    public static final java.lang.String _SZ = "SZ";
    public static final java.lang.String _ZA = "ZA";
    public static final java.lang.String _SD = "SD";
    public static final java.lang.String _SS = "SS";
    public static final java.lang.String _SE = "SE";
    public static final java.lang.String _CH = "CH";
    public static final java.lang.String _SR = "SR";
    public static final java.lang.String _TH = "TH";
    public static final java.lang.String _TW = "TW";
    public static final java.lang.String _TZ = "TZ";
    public static final java.lang.String _TJ = "TJ";
    public static final java.lang.String _PS = "PS";
    public static final java.lang.String _TF = "TF";
    public static final java.lang.String _TL = "TL";
    public static final java.lang.String _TG = "TG";
    public static final java.lang.String _TK = "TK";
    public static final java.lang.String _TO = "TO";
    public static final java.lang.String _TT = "TT";
    public static final java.lang.String _TN = "TN";
    public static final java.lang.String _TC = "TC";
    public static final java.lang.String _TM = "TM";
    public static final java.lang.String _TR = "TR";
    public static final java.lang.String _TV = "TV";
    public static final java.lang.String _UA = "UA";
    public static final java.lang.String _UG = "UG";
    public static final java.lang.String _UY = "UY";
    public static final java.lang.String _UZ = "UZ";
    public static final java.lang.String _VU = "VU";
    public static final java.lang.String _VA = "VA";
    public static final java.lang.String _VE = "VE";
    public static final java.lang.String _VN = "VN";
    public static final java.lang.String _VG = "VG";
    public static final java.lang.String _VI = "VI";
    public static final java.lang.String _WF = "WF";
    public static final java.lang.String _YE = "YE";
    public static final java.lang.String _DJ = "DJ";
    public static final java.lang.String _ZM = "ZM";
    public static final java.lang.String _ZW = "ZW";
    public static final java.lang.String _QU = "QU";
    public static final java.lang.String _XB = "XB";
    public static final java.lang.String _XU = "XU";
    public static final java.lang.String _XN = "XN";
    public static final CountryType2 AF = new CountryType2(_AF);
    public static final CountryType2 AL = new CountryType2(_AL);
    public static final CountryType2 DE = new CountryType2(_DE);
    public static final CountryType2 AD = new CountryType2(_AD);
    public static final CountryType2 AO = new CountryType2(_AO);
    public static final CountryType2 AI = new CountryType2(_AI);
    public static final CountryType2 AQ = new CountryType2(_AQ);
    public static final CountryType2 AG = new CountryType2(_AG);
    public static final CountryType2 SA = new CountryType2(_SA);
    public static final CountryType2 DZ = new CountryType2(_DZ);
    public static final CountryType2 AR = new CountryType2(_AR);
    public static final CountryType2 AM = new CountryType2(_AM);
    public static final CountryType2 AW = new CountryType2(_AW);
    public static final CountryType2 AU = new CountryType2(_AU);
    public static final CountryType2 AT = new CountryType2(_AT);
    public static final CountryType2 AZ = new CountryType2(_AZ);
    public static final CountryType2 BS = new CountryType2(_BS);
    public static final CountryType2 BH = new CountryType2(_BH);
    public static final CountryType2 BD = new CountryType2(_BD);
    public static final CountryType2 BB = new CountryType2(_BB);
    public static final CountryType2 BE = new CountryType2(_BE);
    public static final CountryType2 BZ = new CountryType2(_BZ);
    public static final CountryType2 BJ = new CountryType2(_BJ);
    public static final CountryType2 BM = new CountryType2(_BM);
    public static final CountryType2 BY = new CountryType2(_BY);
    public static final CountryType2 BO = new CountryType2(_BO);
    public static final CountryType2 BA = new CountryType2(_BA);
    public static final CountryType2 BW = new CountryType2(_BW);
    public static final CountryType2 BV = new CountryType2(_BV);
    public static final CountryType2 BR = new CountryType2(_BR);
    public static final CountryType2 BN = new CountryType2(_BN);
    public static final CountryType2 BG = new CountryType2(_BG);
    public static final CountryType2 BF = new CountryType2(_BF);
    public static final CountryType2 BI = new CountryType2(_BI);
    public static final CountryType2 BT = new CountryType2(_BT);
    public static final CountryType2 CV = new CountryType2(_CV);
    public static final CountryType2 KY = new CountryType2(_KY);
    public static final CountryType2 KH = new CountryType2(_KH);
    public static final CountryType2 CM = new CountryType2(_CM);
    public static final CountryType2 CA = new CountryType2(_CA);
    public static final CountryType2 CF = new CountryType2(_CF);
    public static final CountryType2 CC = new CountryType2(_CC);
    public static final CountryType2 CO = new CountryType2(_CO);
    public static final CountryType2 KM = new CountryType2(_KM);
    public static final CountryType2 CG = new CountryType2(_CG);
    public static final CountryType2 CD = new CountryType2(_CD);
    public static final CountryType2 CK = new CountryType2(_CK);
    public static final CountryType2 KP = new CountryType2(_KP);
    public static final CountryType2 KR = new CountryType2(_KR);
    public static final CountryType2 CI = new CountryType2(_CI);
    public static final CountryType2 CR = new CountryType2(_CR);
    public static final CountryType2 HR = new CountryType2(_HR);
    public static final CountryType2 CU = new CountryType2(_CU);
    public static final CountryType2 TD = new CountryType2(_TD);
    public static final CountryType2 CZ = new CountryType2(_CZ);
    public static final CountryType2 CL = new CountryType2(_CL);
    public static final CountryType2 CN = new CountryType2(_CN);
    public static final CountryType2 CY = new CountryType2(_CY);
    public static final CountryType2 CW = new CountryType2(_CW);
    public static final CountryType2 DK = new CountryType2(_DK);
    public static final CountryType2 DM = new CountryType2(_DM);
    public static final CountryType2 DO = new CountryType2(_DO);
    public static final CountryType2 EC = new CountryType2(_EC);
    public static final CountryType2 EG = new CountryType2(_EG);
    public static final CountryType2 AE = new CountryType2(_AE);
    public static final CountryType2 ER = new CountryType2(_ER);
    public static final CountryType2 SK = new CountryType2(_SK);
    public static final CountryType2 SI = new CountryType2(_SI);
    public static final CountryType2 ES = new CountryType2(_ES);
    public static final CountryType2 US = new CountryType2(_US);
    public static final CountryType2 EE = new CountryType2(_EE);
    public static final CountryType2 ET = new CountryType2(_ET);
    public static final CountryType2 FO = new CountryType2(_FO);
    public static final CountryType2 PH = new CountryType2(_PH);
    public static final CountryType2 FI = new CountryType2(_FI);
    public static final CountryType2 FJ = new CountryType2(_FJ);
    public static final CountryType2 FR = new CountryType2(_FR);
    public static final CountryType2 GA = new CountryType2(_GA);
    public static final CountryType2 GM = new CountryType2(_GM);
    public static final CountryType2 GE = new CountryType2(_GE);
    public static final CountryType2 GS = new CountryType2(_GS);
    public static final CountryType2 GH = new CountryType2(_GH);
    public static final CountryType2 GI = new CountryType2(_GI);
    public static final CountryType2 GD = new CountryType2(_GD);
    public static final CountryType2 GR = new CountryType2(_GR);
    public static final CountryType2 GL = new CountryType2(_GL);
    public static final CountryType2 GU = new CountryType2(_GU);
    public static final CountryType2 GT = new CountryType2(_GT);
    public static final CountryType2 GG = new CountryType2(_GG);
    public static final CountryType2 GN = new CountryType2(_GN);
    public static final CountryType2 GQ = new CountryType2(_GQ);
    public static final CountryType2 GW = new CountryType2(_GW);
    public static final CountryType2 GY = new CountryType2(_GY);
    public static final CountryType2 HT = new CountryType2(_HT);
    public static final CountryType2 HM = new CountryType2(_HM);
    public static final CountryType2 HN = new CountryType2(_HN);
    public static final CountryType2 HK = new CountryType2(_HK);
    public static final CountryType2 HU = new CountryType2(_HU);
    public static final CountryType2 IN = new CountryType2(_IN);
    public static final CountryType2 ID = new CountryType2(_ID);
    public static final CountryType2 IR = new CountryType2(_IR);
    public static final CountryType2 IQ = new CountryType2(_IQ);
    public static final CountryType2 IE = new CountryType2(_IE);
    public static final CountryType2 IM = new CountryType2(_IM);
    public static final CountryType2 IS = new CountryType2(_IS);
    public static final CountryType2 IL = new CountryType2(_IL);
    public static final CountryType2 IT = new CountryType2(_IT);
    public static final CountryType2 JM = new CountryType2(_JM);
    public static final CountryType2 JP = new CountryType2(_JP);
    public static final CountryType2 JE = new CountryType2(_JE);
    public static final CountryType2 JO = new CountryType2(_JO);
    public static final CountryType2 KZ = new CountryType2(_KZ);
    public static final CountryType2 KE = new CountryType2(_KE);
    public static final CountryType2 KG = new CountryType2(_KG);
    public static final CountryType2 KI = new CountryType2(_KI);
    public static final CountryType2 KW = new CountryType2(_KW);
    public static final CountryType2 LA = new CountryType2(_LA);
    public static final CountryType2 LS = new CountryType2(_LS);
    public static final CountryType2 LV = new CountryType2(_LV);
    public static final CountryType2 LB = new CountryType2(_LB);
    public static final CountryType2 LR = new CountryType2(_LR);
    public static final CountryType2 LY = new CountryType2(_LY);
    public static final CountryType2 LI = new CountryType2(_LI);
    public static final CountryType2 LT = new CountryType2(_LT);
    public static final CountryType2 LU = new CountryType2(_LU);
    public static final CountryType2 XG = new CountryType2(_XG);
    public static final CountryType2 MO = new CountryType2(_MO);
    public static final CountryType2 MK = new CountryType2(_MK);
    public static final CountryType2 MG = new CountryType2(_MG);
    public static final CountryType2 MY = new CountryType2(_MY);
    public static final CountryType2 MW = new CountryType2(_MW);
    public static final CountryType2 MV = new CountryType2(_MV);
    public static final CountryType2 ML = new CountryType2(_ML);
    public static final CountryType2 MT = new CountryType2(_MT);
    public static final CountryType2 FK = new CountryType2(_FK);
    public static final CountryType2 MP = new CountryType2(_MP);
    public static final CountryType2 MA = new CountryType2(_MA);
    public static final CountryType2 MH = new CountryType2(_MH);
    public static final CountryType2 MU = new CountryType2(_MU);
    public static final CountryType2 MR = new CountryType2(_MR);
    public static final CountryType2 YT = new CountryType2(_YT);
    public static final CountryType2 UM = new CountryType2(_UM);
    public static final CountryType2 MX = new CountryType2(_MX);
    public static final CountryType2 FM = new CountryType2(_FM);
    public static final CountryType2 MD = new CountryType2(_MD);
    public static final CountryType2 MC = new CountryType2(_MC);
    public static final CountryType2 MN = new CountryType2(_MN);
    public static final CountryType2 ME = new CountryType2(_ME);
    public static final CountryType2 MS = new CountryType2(_MS);
    public static final CountryType2 MZ = new CountryType2(_MZ);
    public static final CountryType2 MM = new CountryType2(_MM);
    public static final CountryType2 NA = new CountryType2(_NA);
    public static final CountryType2 NR = new CountryType2(_NR);
    public static final CountryType2 CX = new CountryType2(_CX);
    public static final CountryType2 NP = new CountryType2(_NP);
    public static final CountryType2 NI = new CountryType2(_NI);
    public static final CountryType2 NE = new CountryType2(_NE);
    public static final CountryType2 NG = new CountryType2(_NG);
    public static final CountryType2 NU = new CountryType2(_NU);
    public static final CountryType2 NF = new CountryType2(_NF);
    public static final CountryType2 NO = new CountryType2(_NO);
    public static final CountryType2 NC = new CountryType2(_NC);
    public static final CountryType2 NZ = new CountryType2(_NZ);
    public static final CountryType2 IO = new CountryType2(_IO);
    public static final CountryType2 OM = new CountryType2(_OM);
    public static final CountryType2 NL = new CountryType2(_NL);
    public static final CountryType2 BQ = new CountryType2(_BQ);
    public static final CountryType2 PK = new CountryType2(_PK);
    public static final CountryType2 PW = new CountryType2(_PW);
    public static final CountryType2 PA = new CountryType2(_PA);
    public static final CountryType2 PG = new CountryType2(_PG);
    public static final CountryType2 PY = new CountryType2(_PY);
    public static final CountryType2 PE = new CountryType2(_PE);
    public static final CountryType2 PN = new CountryType2(_PN);
    public static final CountryType2 PF = new CountryType2(_PF);
    public static final CountryType2 PL = new CountryType2(_PL);
    public static final CountryType2 PT = new CountryType2(_PT);
    public static final CountryType2 PR = new CountryType2(_PR);
    public static final CountryType2 QA = new CountryType2(_QA);
    public static final CountryType2 GB = new CountryType2(_GB);
    public static final CountryType2 RW = new CountryType2(_RW);
    public static final CountryType2 RO = new CountryType2(_RO);
    public static final CountryType2 RU = new CountryType2(_RU);
    public static final CountryType2 SB = new CountryType2(_SB);
    public static final CountryType2 SV = new CountryType2(_SV);
    public static final CountryType2 WS = new CountryType2(_WS);
    public static final CountryType2 AS = new CountryType2(_AS);
    public static final CountryType2 KN = new CountryType2(_KN);
    public static final CountryType2 SM = new CountryType2(_SM);
    public static final CountryType2 SX = new CountryType2(_SX);
    public static final CountryType2 PM = new CountryType2(_PM);
    public static final CountryType2 VC = new CountryType2(_VC);
    public static final CountryType2 SH = new CountryType2(_SH);
    public static final CountryType2 LC = new CountryType2(_LC);
    public static final CountryType2 ST = new CountryType2(_ST);
    public static final CountryType2 SN = new CountryType2(_SN);
    public static final CountryType2 RS = new CountryType2(_RS);
    public static final CountryType2 SC = new CountryType2(_SC);
    public static final CountryType2 SL = new CountryType2(_SL);
    public static final CountryType2 SG = new CountryType2(_SG);
    public static final CountryType2 SY = new CountryType2(_SY);
    public static final CountryType2 SO = new CountryType2(_SO);
    public static final CountryType2 LK = new CountryType2(_LK);
    public static final CountryType2 SZ = new CountryType2(_SZ);
    public static final CountryType2 ZA = new CountryType2(_ZA);
    public static final CountryType2 SD = new CountryType2(_SD);
    public static final CountryType2 SS = new CountryType2(_SS);
    public static final CountryType2 SE = new CountryType2(_SE);
    public static final CountryType2 CH = new CountryType2(_CH);
    public static final CountryType2 SR = new CountryType2(_SR);
    public static final CountryType2 TH = new CountryType2(_TH);
    public static final CountryType2 TW = new CountryType2(_TW);
    public static final CountryType2 TZ = new CountryType2(_TZ);
    public static final CountryType2 TJ = new CountryType2(_TJ);
    public static final CountryType2 PS = new CountryType2(_PS);
    public static final CountryType2 TF = new CountryType2(_TF);
    public static final CountryType2 TL = new CountryType2(_TL);
    public static final CountryType2 TG = new CountryType2(_TG);
    public static final CountryType2 TK = new CountryType2(_TK);
    public static final CountryType2 TO = new CountryType2(_TO);
    public static final CountryType2 TT = new CountryType2(_TT);
    public static final CountryType2 TN = new CountryType2(_TN);
    public static final CountryType2 TC = new CountryType2(_TC);
    public static final CountryType2 TM = new CountryType2(_TM);
    public static final CountryType2 TR = new CountryType2(_TR);
    public static final CountryType2 TV = new CountryType2(_TV);
    public static final CountryType2 UA = new CountryType2(_UA);
    public static final CountryType2 UG = new CountryType2(_UG);
    public static final CountryType2 UY = new CountryType2(_UY);
    public static final CountryType2 UZ = new CountryType2(_UZ);
    public static final CountryType2 VU = new CountryType2(_VU);
    public static final CountryType2 VA = new CountryType2(_VA);
    public static final CountryType2 VE = new CountryType2(_VE);
    public static final CountryType2 VN = new CountryType2(_VN);
    public static final CountryType2 VG = new CountryType2(_VG);
    public static final CountryType2 VI = new CountryType2(_VI);
    public static final CountryType2 WF = new CountryType2(_WF);
    public static final CountryType2 YE = new CountryType2(_YE);
    public static final CountryType2 DJ = new CountryType2(_DJ);
    public static final CountryType2 ZM = new CountryType2(_ZM);
    public static final CountryType2 ZW = new CountryType2(_ZW);
    public static final CountryType2 QU = new CountryType2(_QU);
    public static final CountryType2 XB = new CountryType2(_XB);
    public static final CountryType2 XU = new CountryType2(_XU);
    public static final CountryType2 XN = new CountryType2(_XN);
    public java.lang.String getValue() { return _value_;}
    public static CountryType2 fromValue(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        CountryType2 enumeration = (CountryType2)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static CountryType2 fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        return fromValue(value);
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_;}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(CountryType2.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroInformacion.xsd", "CountryType2"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
